# Generated by Django 5.2.5 on 2025-10-08 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoflex', '0002_user_address_user_birth_date_user_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('type_vehicule', models.CharField(choices=[('velo', 'Vélo'), ('trottinette', 'Trottinette'), ('voiture', 'Voiture')], max_length=20)),
                ('capacite', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Station',
                'verbose_name_plural': 'Stations',
            },
        ),
    ]
