# Generated by Django 5.2.5 on 2025-10-29 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoflex', '0003_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='numero_permis',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
