# Generated by Django 5.2.5 on 2025-11-15 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoflex', '0005_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('active', 'Active'), ('annulee', 'Annulée'), ('terminee', 'Terminée'), ('en_cours', 'En cours')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_location', models.DateTimeField(auto_now_add=True)),
                ('date_retour', models.DateTimeField(blank=True, null=True)),
                ('numero_permis_utilise', models.CharField(max_length=5)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('terminee', 'Terminée')], default='en_cours', max_length=20)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='ecoflex.station')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['-date_location'],
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_source', to='ecoflex.location'),
        ),
    ]
