# Generated by Django 5.2.5 on 2025-11-16 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoflex', '0006_alter_reservation_statut_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='location',
        ),
    ]
