# Generated by Django 5.2.5 on 2025-11-19 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoflex', '0007_remove_reservation_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicule', models.CharField(choices=[('velo', 'Vélo'), ('trotinette', 'Trottinette'), ('voiture', 'Voiture')], max_length=20)),
                ('type_abonnement', models.CharField(choices=[('occasionnel', 'Occasionnel'), ('journalier', 'Journalier'), ('mensuel', 'Mensuel'), ('annuel', 'Annuel')], max_length=20)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6)),
                ('unite', models.CharField(max_length=50)),
                ('prix_secondaire', models.CharField(blank=True, max_length=100)),
                ('duree_incluse', models.CharField(blank=True, max_length=100)),
                ('tarif_supplementaire', models.CharField(blank=True, max_length=200)),
                ('depot', models.CharField(blank=True, max_length=100)),
                ('avantages', models.TextField(blank=True)),
                ('populaire', models.BooleanField(default=False)),
                ('duree_minutes', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['vehicule', 'type_abonnement'],
            },
        ),
        migrations.CreateModel(
            name='AbonnementUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to=settings.AUTH_USER_MODEL)),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements_utilisateurs', to='ecoflex.offres')),
            ],
        ),
    ]
