# Generated by Django 5.2.5 on 2025-11-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoflex', '0008_offres_abonnementutilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offres',
            name='vehicule',
            field=models.CharField(choices=[('velo', 'Vélo'), ('trottinette', 'Trottinette'), ('voiture', 'Voiture')], max_length=20),
        ),
    ]
