# Generated by Django 5.2.5 on 2025-11-27 00:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoflex', '0009_alter_offres_vehicule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Adresse invalide.', regex='^[a-zA-Z0-9\\s\\-,\\.#]+$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Ville invalide.', regex="^[a-zA-ZÀ-ÿ\\s'-]+$")]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Format de téléphone invalide.', regex='^(\\+?\\d{1,3}[-.\\s]?)?\\(?\\d{3}\\)?[-.\\s]?\\d{3}[-.\\s]?\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Code postal invalide.', regex='^[A-Z]\\d[A-Z]\\s?\\d[A-Z]\\d$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Province invalide.', regex='^(AB|BC|MB|NB|NL|NS|NT|NU|ON|PE|QC|SK|YT)$')]),
        ),
    ]
